name: dart2js_matrix
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  pool: ^1.3.0

dev_dependencies:
  test: ^0.12.0
